version: '2'
services:
    site1:
        image: nginx
        volumes:
        - ./site.template:/etc/nginx/conf.d/site.template
        - ./public:/var/www/public
        ports:
        - "8080:80"
        expose:
        - "80"
        environment:
        - VIRTUAL_HOST=site1.docker-proxy.localhost
        - NGINX_HOST=site1.docker-proxy.localhost
        - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
    default:
        external:
            name: reverse-proxy_default
